# 백준, java 프로젝트 위치를 입력해주세요.
# ex) /Users/potion/baekjoon/src
srcRoute: /Users/potion/PTDev/intellij_Project/baekjoon/src
packageName: ex
comment: /*\n문제 이름:\n알고리즘:\n자료구조:\n*/\n\n

# 프로그래머스, javascript 프로젝트 위치를 입력해주세요
prgJSRoute: /Users/potion/PTDev/intellij_project/programmers/javascript